# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          context: .
          push: true
          tags: ayocodingit/ayo-mart-service:0.0.1
